# Generated by Django 6.0.1 on 2026-04-04 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=29)),
                ('make', models.CharField(choices=[('BMW', 'bmw'), ('AUDI', 'audi'), ('MERS', 'mers'), ('CHEVROLET', 'chevrolet')], default='bmw', max_length=29)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='cars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'PNG', 'jpg', 'png'])])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2026), django.core.validators.MinValueValidator(1885)])),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cars')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-id'],
            },
        ),
    ]
