# Generated by Django 6.0.3 on 2026-03-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.ImageField(upload_to='cars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.JPG', '.PNG'])]),
        ),
    ]
